language:  python
env:
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=cov
matrix:
  allow_failures:
    - env: TOXENV=cov
install:
   - pip install --quiet --use-mirrors tox
script:
   - tox
after_success:
  - if [ $TOXENV == "cov" ]; then
    pip install --quiet --use-mirrors coveralls;
    coveralls;
    fi